#!/usr/bin/env python3
"""Build the Research and Policy writing pages (English and Spanish) from one data file.

Source of truth: scripts/research_data.json. Edit entries there, then run
    /usr/bin/python3 scripts/build_research.py
from the repository root. The script overwrites
    docs/research/publications.md, docs/research/publications.es.md,
    docs/writing/policy.md, docs/writing/policy.es.md.
Keep the data file aligned with cv-source/ (main.tex, publications-block.tex).
"""
import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = json.loads((ROOT / "scripts" / "research_data.json").read_text(encoding="utf-8"))

TEXT = {
    "en": {
        "with": "with", "and": "and", "in": "In", "abstract": "Abstract",
        "show": "Show all {n}",
        "research_title": "Research",
        "research_intro": ("Journal articles, working papers, book chapters, and commentaries. "
                           "Policy notes and reports are listed under [Policy writing](../writing/policy.md)."),
        "policy_title": "Policy writing and reports",
        "policy_intro": ("Policy notes, briefing notes, and technical reports. "
                         "Journal articles and working papers are listed under [Research](../research/publications.md)."),
    },
    "es": {
        "with": "con", "and": "y", "in": "En", "abstract": "Resumen",
        "show": "Ver los {n}",
        "research_title": "Investigación",
        "research_intro": ("Artículos en revistas, documentos de trabajo, capítulos de libro y comentarios. "
                           "Las notas de política e informes están en [Escritos de política](../writing/policy.md)."),
        "policy_title": "Escritos de política e informes",
        "policy_intro": ("Notas de política, notas informativas e informes técnicos. "
                         "Los artículos y documentos de trabajo están en [Investigación](../research/publications.md)."),
    },
}
HEADER = ("<!-- Generated by scripts/build_research.py from scripts/research_data.json. "
          "Edit the data file and rerun the script; manual edits here are overwritten. -->\n\n")


def loc(value, lang):
    """Return the language-specific version of a field (plain string or {en, es} dict)."""
    if isinstance(value, dict):
        return value.get(lang) or value.get("en")
    return value


def esc(text):
    return html.escape(text, quote=False)


def coauthors(names, lang):
    if not names:
        return ""
    t = TEXT[lang]
    if names[-1] == "et al.":
        joined = ", ".join(names[:-1]) + " et al."
    elif len(names) == 1:
        joined = names[0]
    else:
        joined = ", ".join(names[:-1]) + f" {t['and']} " + names[-1]
    return f"({t['with']} {esc(joined)})"


def meta(it, lang):
    """Citation line after the title: coauthors, then venue, details, year, status."""
    t = TEXT[lang]
    parts = []
    co = coauthors(it.get("coauthors", []), lang)
    venue, details = it.get("venue"), loc(it.get("details"), lang)
    year, status = it.get("year"), loc(it.get("status"), lang)
    if venue:
        v = f"<em>{esc(venue)}</em>"
        if it.get("note") == "in":
            v = f"{t['in']} {v}"
        if details:
            v += (", " if details[:1].isalpha() else " ") + esc(details)
        if year:
            v += f" ({year})"
        parts.append(v)
    elif details:
        parts.append(esc(details) + (f" ({year})" if year else ""))
    elif year:
        parts.append(f"({year})")
    if status:
        parts.append(status)  # may contain <em>; written by hand in the data file
    body = ". ".join(parts)
    return (co + (". " if body else ".") if co else "") + (body + "." if body else "")


def entry(it, lang):
    t = TEXT[lang]
    title = esc(it["title"])
    url = loc(it.get("url"), lang)
    head = f'<a class="pub-title" href="{url}">{title}</a>' if url else f'<span class="pub-title">{title}</span>'
    out = [f'<div class="pub-entry">', f"{head}", f'<span class="pub-meta">{meta(it, lang)}</span>']
    links = [f'<a href="{l["url"]}">{esc(loc(l["label"], lang))}</a>' for l in it.get("links", [])]
    if links:
        out.append('<span class="pub-links">' + " · ".join(links) + "</span>")
    if it.get("abstract"):
        out.append(f'<details class="pub-abstract"><summary>{t["abstract"]}</summary>'
                   f'<p>{esc(it["abstract"])}</p></details>')
    out.append("</div>")
    return "\n".join(out) + "\n"


def research_page(lang):
    t = TEXT[lang]
    lines = [HEADER, f"# {t['research_title']}\n\n", t["research_intro"] + "\n\n"]
    for sec in DATA["research"]:
        lines.append(f"## {loc(sec['title'], lang)} {{#{sec['id']}}}\n\n")
        body = "".join(entry(it, lang) + "\n" for it in sec["items"])
        if sec.get("collapsed"):
            n = len(sec["items"])
            body = (f'<details class="pub-group"><summary>{t["show"].format(n=n)}</summary>\n\n'
                    + body + "</details>\n\n")
        lines.append(body)
    return "".join(lines)


def policy_page(lang):
    t = TEXT[lang]
    lines = [HEADER, f"# {t['policy_title']}\n\n", t["policy_intro"] + "\n\n"]
    lines += [entry(it, lang) + "\n" for it in DATA["policy"]]
    return "".join(lines)


def main():
    targets = {
        "docs/research/publications.md": research_page("en"),
        "docs/research/publications.es.md": research_page("es"),
        "docs/writing/policy.md": policy_page("en"),
        "docs/writing/policy.es.md": policy_page("es"),
    }
    for rel, text in targets.items():
        (ROOT / rel).write_text(text, encoding="utf-8")
        print("wrote", rel)


if __name__ == "__main__":
    main()
